# Generated by Django 5.0.2 on 2024-05-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userthread',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='posts'),
        ),
    ]
