# Generated by Django 5.0.2 on 2024-05-05 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userthread_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userthread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
